markdown: kramdown

exclude:
  - api
  - bower.json
  - bower_components
  - css
  - docker
  - docker-compose.yml.dist
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile
  - js
  - lib
  - node_modules
  - package.json
  - Rakefile
  - vendor

include:
  - .nojekyll
